services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    volumes:
      - ./BE/src:/app/src
    image: backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    image: frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./FE/src:/app/src
      - ./FE/public:/app/public
    depends_on:
      - backend

volumes:
  pgdata: {}
